app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
logout: 
    path: /logout

carpage:
    path: /samochody
    defaults: { _controller: AppBundle:Page:car }
    
ajaxcarpage:
    path: /ajax/samochody/update/data"
    defaults: { _controller: AppBundle:Ajax:findCar }